"""added session_token to sessions table

Revision ID: 0c594574c6aa
Revises: ba698ee5f71f
Create Date: 2026-10-04 13:41:29.335559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c594574c6aa'
down_revision: Union[str, Sequence[str], None] = 'ba698ee5f71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_token', sa.String(), nullable=False))
    op.alter_column('sessions', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using='id::integer')
    op.create_unique_constraint(None, 'sessions', ['session_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sessions', type_='unique')
    op.alter_column('sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('sessions', 'session_token')
    # ### end Alembic commands ###
